name: Terraform Plan and Apply

on:
  push:
    branches:
      - master # Executa o pipeline apenas no branch main
  pull_request:
    branches:
      - master # Executa o pipeline em pull requests para o branch main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # Usa a secret AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Usa a secret AWS_SECRET_ACCESS_KEY

    steps:
      # 1. Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar o LocalStack
      - name: Start LocalStack
        run: |
          docker run -d --name localstack -p 4566:4566 -e SERVICES=s3,ec2 localstack/localstack
          sleep 10  # Aguarda o LocalStack inicializar

      # 3. Criar o bucket S3 no LocalStack
      - name: Create S3 Bucket
        run: |
          aws --endpoint-url=http://localhost:4566 --region=us-east-1 s3 mb s3://meu-bucket-terraform-state

      # 3. Configurar o Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Versão do Terraform

      # 4. Inicializar o Terraform
      - name: Terraform Init
        run: terraform init

      # 5. Validar o código Terraform
      - name: Terraform Validate
        run: terraform validate

      # 6. Planejar a infraestrutura
      - name: Terraform Plan
        run: terraform plan

      # 7. Aplicar a infraestrutura (apenas no branch main)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
